export const enum ListTextContent {
  COPYRIGHT = '© Copyright 2023',
  SIGN_UP = 'Sign up',
  SIGN_IN = 'Sign in',
  EMAIL = 'EMAIL',
  PASSWORD = 'PASSWORD',
  LOGIN = 'LOGIN',
  ADDRESS = 'STREET',
  BIRTHDAY = 'DATE OF BIRTH',
  LAST_NAME = 'LAST NAME',
  FIRST_NAME = 'FIRST NAME',
  COUNTRY = 'COUNTRY',
  CITY = 'CITY',
  POST = 'POSTCODE',
  SHIPPING_ADDRESS = 'Shipping address',
  BILLING_ADDRESS = 'Billing address',
}
