export const enum ListClasses {
  HEADER = 'bg-blue-color',
  HEADER_CONTAINER = 'flex justify-between items-center w-full p-3',
  HEADER_BUTTONS = 'flex w-40 justify-between items-center sm-s:w-52 lg-l:w-56 2xl:w-80',
  BASKET_ICON = 'cursor-pointer h-8 w-8',
  SEARCH_ICON = 'cursor-pointer h-6 w-6',
  BUTTON_SIGN_UP = 'text-white text-xs sm-s:text-sm lg-l:text-lg 2xl:text-2xl',
  BUTTON_SIGN_IN = 'text-black text-xs sm-s:text-sm lg-l:text-lg 2xl:text-2xl',
  MAIN = 'flex-auto bg-main-background',
  FOOTER = 'bg-footer-color flex justify-center px-3',
  FOOTER_CONTENT = 'flex',
  FOOTER_LINKS = 'flex flex-col',
  FOOTER_LINKS_TEXT = 'text-xs text-white py-1.5',
  LOGIN_IMG = 'rounded-radius-sm w-24 h-24 absolute -top-8 left-img-calc',
  LOGIN_TITLE = 'text-white text-center text-2xl pb-5',
  FORM_LOGIN = 'form w-72 h-85h rounded-xl bg-form-color absolute top-50% left-50% py-20 px-8',
  INPUT = 'w-full text-white border-0 outline-0 bg-transparent border-b border-white placeholder:text-sm placeholder:opacity-40 mb-2 caret-white',
  INPUT_NAME = 'mr-5 w-21w text-white border-0 outline-0 bg-transparent border-b border-white placeholder:text-sm placeholder:opacity-40 mb-2 caret-white',
  LABEL = 'text-input-color text-xx-s font-bold',
  LABEL_LOGIN = 'text-input-color text-sm font-bold',
  SUBMIT_BUTTONS = 'hover:bg-neon-color text-white w-full border-2 rounded-3xl border-neon-color cursor-pointer mt-2',
  FORM_REGISTRATION = 'form overflow-y-auto form w-80 h-100h rounded-xl bg-form-color absolute top-50% left-50% py-6 px-6',
  DIV = 'flex items-center',
  LABEL_MR = 'text-input-color text-xx-s font-bold mr-2',
  DIV_CONTAINER = 'flex justify-between w-full items-center',
  LABEL_SELECT = 'text-input-color text-xx-s font-bold w-127px',
  INPUT_SELECT = 'w-full text-white border-0 outline-0 bg-transparent border-b border-white placeholder:text-sm placeholder:opacity-40 caret-white pt-0.7rem',
}
