export const enum ListAttributes {
  SRC = 'src',
  ALT = 'alt',
  ID = 'id',
  TYPE = 'type',
  PLACEHOLDER = 'placeholder',
  FOR = 'for',
  VALUE = 'value',
  HREF = 'href',
  STYLE = 'style',
  STEP = 'step',
  MIN = 'min',
  MAX = 'max',
  DISABLED = 'disabled',
  LOADING = 'loading',
}
