export const enum ListTags {
  HEADER = 'header',
  CONTAINER = 'div',
  BUTTON = 'button',
  INPUT = 'input',
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',
  H6 = 'h6',
  SPAN = 'span',
  FOOTER = 'footer',
  MAIN = 'main',
  IMG = 'img',
  FORM = 'form',
  LABEL = 'label',
  LINK = 'a',
  PARAGRAPH = 'p',
  SELECT = 'select',
  OPTION = 'option',
  UL = 'ul',
}
