export const enum ListTextContent {
  COPYRIGHT = '© Copyright 2023',
  SIGN_UP = 'Sign up',
  SIGN_IN = 'Sign in',
  EMAIL = 'EMAIL',
  PASSWORD = 'PASSWORD',
  LOGIN = 'LOGIN',
  ADDRESS = 'STREET',
  BIRTHDAY = 'DATE OF BIRTH',
  LAST_NAME = 'LAST NAME',
  FIRST_NAME = 'FIRST NAME',
  COUNTRY = 'COUNTRY',
  CITY = 'CITY',
  POST = 'POSTCODE',
  SHIPPING_ADDRESS = 'Shipping address',
  BILLING_ADDRESS = 'Billing address',
  ERROR_404_HEADING = 'ERROR 404',
  ERROR_404_DESCRIPTION = 'The requested URL was not found on this server.',
  ERROR_404_BUTTON = 'Go to main page',
}
