export const enum ListAttributesValues {
  LOGO = 'logo',
  EMAIL = 'email',
  TEXT = 'text',
  FORM_PASSWORD = 'form-password',
  PLACEHOLDER_EMAIL = 'Enter your email',
  PLACEHOLDER_PASSWORD = 'Enter your password',
  BUTTON = 'button',
  SIGN_IN = 'Sign in',
  SIGN_UP = 'Sign up',
  LOGIN = 'login',
  ADDRESS = 'address',
  DATE = 'date',
  COUNTRY = 'country',
  CITY = 'city',
  POSTCODE = 'postcode',
  LAST_NAME = 'last-name',
  FIRST_NAME = 'first-name',
  CHECKBOX = 'checkbox',
}
