export const enum ListClasses {
  HEADER = 'bg-blue-color',
  HEADER_CONTAINER = 'flex justify-between items-center w-full p-3',
  HEADER_BUTTONS = 'flex w-40 justify-between items-center sm-s:w-52 lg-l:w-56 2xl:w-80',
  BASKET_ICON = 'cursor-pointer h-8 w-8',
  SEARCH_ICON = 'cursor-pointer h-6 w-6',
  BUTTON_SIGN_UP = 'text-white text-xs sm-s:text-sm lg-l:text-lg 2xl:text-2xl',
  BUTTON_SIGN_IN = 'text-black text-xs sm-s:text-sm lg-l:text-lg 2xl:text-2xl',
  MAIN = 'flex-auto bg-main-background opacity-40',
  FOOTER = 'bg-blue-color flex justify-center px-3',
  FOOTER_CONTENT = 'flex',
  FOOTER_LINKS = 'flex flex-col',
  FOOTER_LINKS_TEXT = 'text-xs py-1.5',
  FORM = 'form w-72 h-85h rounded-xl bg-login-color absolute top-50px left-50px py-20 px-8',
  INPUT_USERNAME = 'm-12 border-0 outline-0 bg-transparent border-b border-white',
  BG = 'bg-lime-500 w-40 h-40',
}
