export const enum ListAttributesValues {
  LOGO = 'logo',
  EMAIL = 'email',
  TEXT = 'text',
  FORM_PASSWORD = 'form-password',
  PLACEHOLDER_EMAIL = 'Enter your email',
  PLACEHOLDER_PASSWORD = 'Enter your password',
  PLACEHOLDER_ADDRESS = 'Enter your address',
  PLACEHOLDER_SURNAME = 'Enter your surname',
  PLACEHOLDER_NAME = 'Enter your name',
  BUTTON = 'button',
  SIGN_IN = 'Sign in',
  SIGN_UP = 'Sign up',
  LOGIN = 'login',
  ADDRESS = 'address',
  BIRTHDAY = 'date',
  SECOND_NAME = 'second-name',
  FIRST_NAME = 'first-name',
}
